### ISSUE TITLE
mdc-textfield: TypeError if value is null

### ISSUE THREAD

**Issue by mloar** [onehilltech/ember-cli-mdc#11]
The recent change [d55fcae](https://github.com/onehilltech/ember-cli-mdc/commit/d55fcae03e4241d03dc371ecba530e5aff72aed6) introduced a bug where a TypeError will occur in _checkValue if value is null.
`   if (document.activeElement !== input && value !== undefined && value !== value.value) {`

**Comment by hilljh82** [comment]
@mloar There seems to be a typo in the conditional statement that I need to check. But, do you have an example that is causing the issue? Is it when value=null in the template?

**Comment by mloar** [comment]
In my case I'm binding value to a DS.attr('string') on a model. My backend returns nulls in the JSON, which get passed through the model into the template. Probably not the best design, but hasn't been a problem otherwise.

**Comment by hilljh82** [comment]
@mloar Thanks, this is helpful.

**Comment by hilljh82** [comment]
@mloar 0.74.17 has the fix.

**Comment by jamesstaub** [comment]
I am experiencing a similar problem with mdc-textfield 0.78. if i pass a null property to `value` (like when a related model has not resolved.

![Screen Shot 2019-05-09 at 10 47 05 AM](https://user-images.githubusercontent.com/1205113/57464215-56262e80-724a-11e9-817a-b94ef89d2943.png)

**Comment by hilljh82** [comment]
@jamesstaub This is the same problem, but in a different location. It seems that `2.0.0` has made some changes at the foundation level that is not liking `null` values.

**Comment by hilljh82** [comment]
@jamesstaub Upon further investigation, this is actually a completely different issue altogether. The underlying `material-components-web` does not like a `null` value. Ideally, the underlying foundation component should check for `null` value before trying to set the character count. I am going to submit a patch to `material-components-web` to handle this scenario. 

In the meantime, I am trying to figure out how to best handle this situation. Not setting the value to `null` in the foundation component could lead to unwanted behavior, such as not reseting the input. Translating `null` values to an empty string could present a problem if the native input triggers a change event—resulting the bound attribute to convert from `null` to an empty string. I will get the latter approach a try and see if this is a viable solution.

**Comment by hilljh82** [comment]
`0.78.1` patch contains a fix for this problem.

**Comment by jamesstaub** [comment]
awesome thank you!
