### ISSUE TITLE
Change default typography (remove Roboto)

### ISSUE THREAD

**Issue by waissbluth** [onehilltech/ember-cli-mdc#14]
According to [the docs](https://github.com/onehilltech/ember-cli-mdc/tree/master/packages/mdc-typography#roboto-font), "The typography package automatically includes links to the Roboto fonts in your application.".

Is there an official way to avoid this? The `mdc-typography` gets added on install, but nothing seems to break removing it from the `package.json`.

**Comment by hilljh82** [comment]
@waissbluth Could you please clarify your question/comment? It's unclear what you are wanting to remove, or trying to accomplish.

**Comment by waissbluth** [comment]
@hilljh82, I am trying to:
a) set a font other than Roboto as a default for all components, and
b) stop the message `Linking Roboto fonts with the application.` that shows up in the build process (it actually shows up twice for every build, but that is probably a separate issue)

**Comment by hilljh82** [comment]
@waissbluth 

(a) Can you not use [this approach as recommend in material-components-web](https://github.com/material-components/material-components-web/tree/master/packages/mdc-typography#overriding-styles) to change the default font for all components? Just place what they recommend at the top of your `app.scss` file before any of the imports.

(b) I have been trying to figure out how to address this issue, but I think it's an ember-cli issue. From what I can tell, this causes the typography/fonts to appear in both the `application.css` and `vendor.css` files. It's somewhat annoying, but does not break anything or cause anything bad.

**Comment by waissbluth** [comment]
Thank you @hilljh82, (a) works. It still would be nice not to load Roboto at all, but this will do.

**Comment by hilljh82** [comment]
@waissbluth Great! 

Its understanable to not link the fonts if you are using a custom font. We will look into supporting this feature via environment configuration.

**Comment by hilljh82** [comment]
@waissbluth `0.78.2` allows to you disable linking of Roboto font too.

  https://github.com/onehilltech/ember-cli-mdc/tree/master/packages/mdc-typography#disable-integration
