### ISSUE TITLE
mdc-radio?

### ISSUE THREAD

**Issue by jamesstaub** [onehilltech/ember-cli-mdc#20]
Is there any plan to implement the mdc-radio component?

**Comment by hilljh82** [comment]
@jamesstaub I was working on implementing `mdc-radio` support, but stopped since I found a better UI design instead of using a radio button for my personal projects. Is this something you need urgently for your project?

**Comment by jamesstaub** [comment]
We'd like to use it yes, but can make do designing our own for the time being. I'll keep an eye out in case you decide to implement it in the future. Thanks.

**Comment by victorcasignia** [comment]
@jamesstaub If you still need mdc-radio, I've implemented it on my fork. Will probably PR this if I get the time to remove the ember-radio-button package dependency I used.

**Comment by jamesstaub** [comment]
thanks! I'll take a look

**Comment by hilljh82** [comment]
@jamesstaub @victorcasignia This is great! BTW, 1.0.0, will have support for both radio buttons and data tables.

**Comment by dnix** [comment]
Hello! Are there any updates to having standalone `mdc-radio` in 1.0.0? Thanks in advance!

**Comment by hilljh82** [comment]
@dnix Yes, it is still planned, and will happen. Thanks for inquiring!

**Comment by hilljh82** [comment]
This component has been implemented. Its in the [ember-cli-mdc-radio](https://github.com/onehilltech/ember-cli-mdc/tree/master/packages/mdc-radio) package.
