### ISSUE TITLE
will there be a octane version anytime soon? just interested

### ISSUE THREAD

**Issue by ahemed-haneen** [onehilltech/ember-cli-mdc#28]

**Comment by hilljh82** [comment]
@TheLooseCannon Yes, there will be an Octane version. I am in the planning stages right now.

**Comment by hilljh82** [comment]
@TheLooseCannon We plan to begin working on the Octane version starting at the end of May not that we have a much better understanding of what has changed.

**Comment by makepanic** [comment]
Hi, did you have any time to work on an octane version?

I could start working on it if you want to.

**Comment by hilljh82** [comment]
@TheLooseCannon The octane version is finally complete. It was a complete rewrite of all the components.
