### ISSUE TITLE
DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.

### ISSUE THREAD

**Issue by davidbilling** [onehilltech/ember-cli-mdc#38]
This warning appears in most packages. Will this be fixed in upcoming versions?

DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div(notched-outline-variables.$label-box-height, 2)

More info and automated migrator: https://sass-lang.com/d/slash-div

   ╷
36 │   @return $text-field-height / 2 + notched-outline-variables.$label-box-height / 2;
   │                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
    node_modules/@material/textfield/_variables.scss 36:36                                                 get-outlined-label-position-y()
    node_modules/@material/textfield/_variables.scss 97:5                                                  @forward
    node_modules/@material/textfield/mdc-text-field.import.scss 16:1                                       @import
    /tmp/broccoli-9459a0Mr066hjvWo/out-710-broccoli_merge_trees_full_application/app/styles/app.scss 35:9  root stylesheet

**Comment by hilljh82** [comment]
@davidbilling We have noticed this as well, but from what we can tell this is associated with material-component-web. We plan on updating to the latest version (11.0), and hopefully this issue goes away. If not, we may have to bind to a version of dart-sass that supports this usage in material-component-web.

**Comment by davidbilling** [comment]
@hilljh82 Great! Looking forward to the 11,0 upgrade. You made great addons.

**Comment by hilljh82** [comment]
@davidbilling This has been fixed for `ember-cli-mdc@^2.0.0`. I had to bind sass to version 1.30.0.
