### ISSUE TITLE
Ember Addon Install Problem

### ISSUE THREAD

**Issue by pathway27** [onehilltech/ember-cli-mdc#39]
Hey, I just did a `ember install ember-cli-mdc`, and I get this error:

```
Command failed with exit code 1: yarn add --dev ember-cli-mdc-typography@^2.3.4 --non-interactive
error Couldn't find any versions for "ember-cli-mdc-typography" that matches "^2.3.4"
```

Is there something wrong with the versioning of this package?

**Comment by hilljh82** [comment]
@pathway27 Is it safe to assume that the top-level command you ran was

    yarn add --dev ember-cli-mdc-typography@^2.3.4 --non-interactive

**Comment by pathway27** [comment]
Nope, I ran `ember install ember-cli-mdc` and it's stuck at a different package now:

```
...
Command failed with exit code 1: yarn add --dev ember-cli-mdc-rtl@^2.3.4 --non-interactive
error Couldn't find any versions for "ember-cli-mdc-rtl" that matches "^2.3.4"
```

I'm wondering why it tries to install version `2.3.4`?

**Comment by hilljh82** [comment]
@pathway27 This add-on uses a specialized blueprint that tries to speed up the installation when compared to just installing it the traditional way. We also recommend that you only install the add-ons you need, and not install `ember-cli-mdc`. For example, if you need buttons, then install:

    ember install ember-cli-mdc-button@^2.0.0

**Comment by hilljh82** [comment]
@pathway27 You can find list of add-ons here:

https://github.com/onehilltech/ember-cli-mdc/tree/master/packages

Just append `ember-cli-` to the beginning of the package.

BTW, I am removing the part in the README where it gives instructions to install all packages. I didn't realize it was still present in the README.

**Comment by hilljh82** [comment]
I am closing this issue since it is assumed @pathway27 issue has been addressed. If not, please reopen this issue.
