### ISSUE TITLE
Problem with npmjs versioning

### ISSUE THREAD

**Issue by mtsgeneroso** [onehilltech/ember-cli-mdc#41]
I've been helping some coworkers install these components on their projects. An annoying thing has been happening when we try to install the latest stable version and by mistake we get an alpha.

![image](https://user-images.githubusercontent.com/18399145/145460353-f16214ec-77db-4390-906f-9a34a58b56c3.png)

Is it possible to follow the @material-components pattern?

![image](https://user-images.githubusercontent.com/18399145/145460437-056b9efc-9dff-4f59-98a4-f073a912d65d.png)

**Comment by hilljh82** [comment]
@mtsgeneroso Unfortunately, we do not want to do that since we do not release and/or update at the same times. Make sure you are adding the version to the ember addon being installed:

https://github.com/onehilltech/ember-cli-mdc#installation

**Comment by mtsgeneroso** [comment]
@hilljh82 OK, got it.
