### ISSUE TITLE
The container class for MdcDataTableHeaderCell differs between HBS and SCSS when 'numeric' is defined

### ISSUE THREAD

**Issue by mtsgeneroso** [onehilltech/ember-cli-mdc#49]
Hi!

I just wanted to bring this up – I’m working with numeric columns and noticed an inconsistency.

Here are the links for reference:

SCSS (`__container`): https://github.com/onehilltech/ember-cli-mdc/blob/31224fbaab1ee6babc06c260c888210ebcf1e3b5/packages/mdc-data-table/addon/styles/addon.scss#L28

HBS (`__content`): https://github.com/onehilltech/ember-cli-mdc/blob/31224fbaab1ee6babc06c260c888210ebcf1e3b5/packages/mdc-data-table/addon/components/mdc-data-table-header-cell.hbs#L10

**Comment by hilljh82** [comment]
Fixed! I have created a new release.
